version: '3.8'

services:

  nginx:
    image: nginx:1.20.2-perl
    volumes:
      - ./www:/usr/share/nginx/html:ro
    ports:
      - 55580:80
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1

  web:
    build: .
    volumes:
      - .:/base
    depends_on:
      - nginx
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    #stdin_open: true    # debug
    #tty: true           # debug
    #command: bash -c 'env > /etc/environment && bash' # debug

